scss_files: 'assets/styles/scss/*/*.scss'

exclude:
  - 'assets/styles/scss/*/*/*'
  - 'assets/styles/scss/components/_syntax-highlighting.scss'
  - 'assets/styles/scss/base/_normalize.scss'

linters:
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
  VendorPrefix:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  SelectorFormat:
    enabled: false
  Comment:
    enabled: false
