title: Savas
email: info@savaslabs.com
description: > 
  A Drupal-centric web development and design shop anchored in Durham.
baseurl: "" 
url: "http://savaslabs.com"
twitter_username: savas_labs 
github_username: savaslabs
markdown: kramdown
sass:
  sass_dir: assets/styles/_scss
collections:
  team:
    output: true
    permalink: /team/:path/
  work:
    output: true
    permalink: /work/:path/