# Basic Info
title: Savas
email: info@savaslabs.com
description: > 
  A Drupal-centric web development and design shop anchored in Durham, NC.
baseurl: "" 
url: "http://savaslabs.com"
comment_server_url: http://comments.savasdev.com
comment_server_enabled: 0

# Nav links
navigation:
  - title: Who we are
    url: /team
  - title: What we do
    url: /what-we-do
  - title: Our work
    url: /work
  - title: Training
    url: /drupal-training
  - title: News
    url: /news
  - title: Contact
    url: /contact

# Professional and social media links
twitter_username: savas_labs 
github_username: savaslabs

# Languages and syntax highlighting
markdown: kramdown
sass:
  sass_dir: assets/styles/_scss
highlighter: pygments

# Blog
paginate: 6
paginate_path: "/news/:num/"

# For Travis CI
exclude: [vendor]

# Collections
collections:
  team:
    output: true
    permalink: /team/:path/
  work:
    output: true
    permalink: /work/:path/

# Gems
gems:
  - jekyll-sitemap
